### ISSUE TITLE
Enable dependabot on dependency

### ISSUE THREAD

**Issue by glefloch** [quarkiverse/quarkus-mockk#3]
Hi @gastaldi, it looks like dependabot is not enable by default and I don't have access to the `settings` part of the project. 
Is it possible for you to enable it? Thanks!

**Comment by gastaldi** [comment]
@glefloch it is already enabled organization-wide, not sure what's causing it to not be triggered

**Comment by gastaldi** [comment]
Looks like it's working now (see https://github.com/quarkiverse/quarkus-mockk/pull/9 - probably needed a small bump in the descriptor to work), I'll close this issue now

**Comment by glefloch** [comment]
Great thanks!
